### ISSUE TITLE
Enable Travis repo

### ISSUE THREAD

**Issue by palfrey** [FJNR-inc/dry-rest-permissions#19]
There's a link to the build, but the repo (https://travis-ci.org/github/FJNR-inc/dry-rest-permissions) isn't enabled

**Comment by RignonNoel** [comment]
Hi @palfrey, thanks for the issue.

I just checked and effectively Travis has been disabled on this repository, i just turned it on. I think it's due to a manual error during transition between tracis-ci.org and travis-ci.com since `.org` will disappear soon.

Here is the new link: https://www.travis-ci.com/github/FJNR-inc/dry-rest-permissions/

I've updated the README to be sure everybody have the new link.

If everything is good for you i will close the issue.

**Comment by palfrey** [comment]
LGTM
